[Hana]
address = hanabtrust
port = 30015
user = SBOADMIN
password = Btwsx76!
; schema = UPDATEROW_TEST_BTRUST
schema = SBO_BTRUST_LIVE
[POsqlserver]
name = btrust
host = WEBAPP\SQLEXPRESS
password = admin@btrust
database = WarehousePO
[Current]
begin = 0
end = 0
[Warning]
begin = -1
end = -1
[Danger]
begin = -100000
end = -7
[duration]
second = 30
[Week]
weekBegin = -6
weekEnd = 0
[ExpiredInterval]
intervals = 1,2,3
[ExpiredKinds]
kinds = grocery,frozen
[ExpiredKind]
grocery = 133,135
frozen = 134
[postgresql]
username = saleor
host = 172.16.30.8
port = 5432
password = saleor
database = Sales_DB
[HOsqlserver]
name = schedulejob
host = WEBAPP
password = ddME5YA06
database = STORESQLHO
[stores]
store = MS,NY,TE,MT
description=Mississauga B1,North York B2,Terra,Montreal
[Storesqlserver]
name = schedulejob,andrew.pan1,andrewpan,andrew.pan
host = WEBAPP,10.2.10.90\LOGI2023B,10.3.10.90\LOGI2023,10.5.10.90\LOGI
password = ddME5YA06,Apan,Apan,Apan
database = STORESQLB1,LogiDB,LogiDB,LogiDB