[Hana]
address = hanabtrust
port = 30015
user = SBOADMIN
password = Btwsx76!
; schema = UPDATEROW_TEST_BTRUST
schema = SBO_BTRUST_LIVE
[POsqlserver]
name = btrust
host = WEBAPP\SQLEXPRESS
password = admin@btrust
database = WarehousePO
[Current]
begin = 0
end = 0
[Warning]
begin = -1
end = -1
[Danger]
begin = -100000
end = -7
[duration]
second = 30
[Week]
weekBegin = -6
weekEnd = 0
[ExpiredInterval]
intervals = 1,2,3
[ExpiredKinds]
kinds = grocery,frozen
[ExpiredKind]
grocery = 133,135
frozen = 134